stages:
  - build
  - test

image: maven:3-amazoncorretto-21

build-job:
  stage: build
  script:
    - echo "Building the project..."
    - cd backend
    - mvn clean compile
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

test-job:
  stage: test
  script:
    - echo "Running tests..."
    - cd backend
    - mvn -B clean test
  artifacts:
    reports:
      junit:
        - target/surefire-reports/*.xml
      coverage_report:
        coverage_format: cobertura
        path: target/site/cobertura/coverage.xml
    paths:
      - target/surefire-reports/
      - target/site/cobertura/
    expire_in: 1 day
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
